# Generated by Django 4.0.3 on 2022-04-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_alter_post_options_rename_created_post_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='text',
        ),
    ]
